FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14

RUN  bash -c 'npm install gulp-cli yo generator-teams @pnp/cli-microsoft365 --global --production --quiet --no-progress' 

CMD [ "bash", "-l" ]

